-- Alpha waitlist leads captured when deployed generation is gated.

create table if not exists public.alpha_signups (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  organization text,
  additional_info text,
  source text not null default 'web',
  metadata_json jsonb not null default '{}'::jsonb,
  created_at text not null
);

create index if not exists idx_alpha_signups_email
  on public.alpha_signups (lower(email));

create index if not exists idx_alpha_signups_created_at
  on public.alpha_signups (created_at);
